[package]
name = "pixel_graphics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.26.1"
pixels = "0.9.0"
glam = "0.20.5"
image = "0.24.1"
tobj = "3.2.2"
quad-rand = "0.2.1"